language: node_js
node_js:
  - '6'
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  'on':
    branch: master
    node: '5'
env:
  global:
    - secure: >-
        I1pTUsVLISsCdkG5T25L50Aw/S4gbjXCDCe40E2HI/tlauQGJ4gM9+GrjbOt+WA5gcWM8MmcHASlWhAmZzG6gPd45L8w2Z2WtMumZgtGur5SQMx4TBnhh0i0g4gpYNWQ2Ij2OD1KAFFc9m3EAD/f6Qb64yypACcEl7zwOhQXeE1QDH+eqCCoGZ9GDhsV5JzrSLxM0p6QdCQXb8VhPbyzV2b25VR8/xnhrXfjLWwtimMgKzD40d3gHmN4nlHkF2WP0u5EtJ7+z1FwX7GqmE/vGCYi47dnsJsivPD8Wd40MXLTzqxNe7cBmqR1ujPJSNcKWAUGoEzf0dB885OQjBgJHTPcmidkxpU2XqgN8lCYkhTpARi5pG5oLS0Ghhix3qQu7B+2AcpYDZm6CpIvqAWSyyWkekFTRaHEmvZIHHkLNo5wy0cz0AYf0JqJZ0wPxZily+UHTC/YFiW4aD3uULrMILwpaeKHFAKT6ObItcRWzVcH5DRIcKa0WtvkyBMTk1ITHdCEohE0BHxa7gprtygI3LmNimG+aXKFhw3i/JkRLss085KrHZb3wpMdS5tdmLghoN0e8Px5qM0UToYPcya461EWa/upfWzjzAntbK5uv975stVoMxx7eJdACo44d8k/833d4tOIF7JNOSMmPsdTuDe0W5hwwmbQjmOXgRkW4IQ=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/constellates/dot-com.git
